/**
 * Blockout recoil data — recoil profiles per weapon.
 *
 * BLOCKOUT-02H: First visible blockout vehicles (placeholder data).
 * BLOCKOUT-05H+: Extended with pixel kickback fields for visual recoil.
 * Smoky/Railgun/Thunder have meaningful visual recoil.
 * Other weapons have minimal/placeholder values for future steps.
 */

import type { RecoilProfile } from './blockoutProfiles';

/** Recoil profiles keyed by weapon ID. */
export const RECOIL_PROFILES: Record<string, RecoilProfile> = {
  smoky: {
    weaponId: 'smoky',
    barrelKickback: 3,
    turretKickback: 1,
    bodyImpulse: 0.5,
    recoveryMs: 200,
    cameraShake: false,
    barrelKickbackPx: 4,
    turretKickbackRad: 0.03,
    bodyImpulsePx: 1.5,
  },
  thunder: {
    weaponId: 'thunder',
    barrelKickback: 4,
    turretKickback: 2,
    bodyImpulse: 1.0,
    recoveryMs: 300,
    cameraShake: false,
    barrelKickbackPx: 5,
    turretKickbackRad: 0.05,
    bodyImpulsePx: 2.5,
  },
  railgun: {
    weaponId: 'railgun',
    barrelKickback: 6,
    turretKickback: 3,
    bodyImpulse: 2.0,
    recoveryMs: 400,
    cameraShake: false,
    barrelKickbackPx: 7,
    turretKickbackRad: 0.07,
    bodyImpulsePx: 4.0,
  },
  shaft: {
    weaponId: 'shaft',
    barrelKickback: 7,
    turretKickback: 3,
    bodyImpulse: 2.5,
    recoveryMs: 500,
    cameraShake: false,
    barrelKickbackPx: 8,
    turretKickbackRad: 0.08,
    bodyImpulsePx: 5.0,
  },
  flamethrower: {
    weaponId: 'flamethrower',
    barrelKickback: 0.5,
    turretKickback: 0.2,
    bodyImpulse: 0.1,
    recoveryMs: 50,
    cameraShake: false,
    barrelKickbackPx: 0.5,
    turretKickbackRad: 0.005,
    bodyImpulsePx: 0.2,
  },
  freeze: {
    weaponId: 'freeze',
    barrelKickback: 0.5,
    turretKickback: 0.2,
    bodyImpulse: 0.1,
    recoveryMs: 50,
    cameraShake: false,
    barrelKickbackPx: 0.5,
    turretKickbackRad: 0.005,
    bodyImpulsePx: 0.2,
  },
  isida: {
    weaponId: 'isida',
    barrelKickback: 0.3,
    turretKickback: 0.1,
    bodyImpulse: 0.05,
    recoveryMs: 30,
    cameraShake: false,
    barrelKickbackPx: 0.3,
    turretKickbackRad: 0.003,
    bodyImpulsePx: 0.1,
  },
  vulcan: {
    weaponId: 'vulcan',
    barrelKickback: 0.8,
    turretKickback: 0.3,
    bodyImpulse: 0.15,
    recoveryMs: 80,
    cameraShake: false,
    barrelKickbackPx: 1.0,
    turretKickbackRad: 0.01,
    bodyImpulsePx: 0.5,
  },
  twins: {
    weaponId: 'twins',
    barrelKickback: 1.0,
    turretKickback: 0.4,
    bodyImpulse: 0.2,
    recoveryMs: 100,
    cameraShake: false,
    barrelKickbackPx: 1.5,
    turretKickbackRad: 0.015,
    bodyImpulsePx: 0.8,
  },
  ricochet: {
    weaponId: 'ricochet',
    barrelKickback: 1.2,
    turretKickback: 0.5,
    bodyImpulse: 0.3,
    recoveryMs: 120,
    cameraShake: false,
    barrelKickbackPx: 2.0,
    turretKickbackRad: 0.02,
    bodyImpulsePx: 1.0,
  },
  hammer: {
    weaponId: 'hammer',
    barrelKickback: 5,
    turretKickback: 2.5,
    bodyImpulse: 1.5,
    recoveryMs: 350,
    cameraShake: false,
    barrelKickbackPx: 6,
    turretKickbackRad: 0.06,
    bodyImpulsePx: 3.0,
  },
};
