/**
 * Blockout damage data — damage profiles per weapon.
 *
 * BLOCKOUT-02H: First visible blockout vehicles.
 * BLOCKOUT-07H+: Added damageKind, rangePx, and hit detection fields
 * for all 11 weapon families. Dev/arena-only damage placeholders.
 */

import type { DamageProfile } from './blockoutProfiles';

/** Damage profiles keyed by weapon ID. */
export const DAMAGE_PROFILES: Record<string, DamageProfile> = {
  smoky: {
    weaponId: 'smoky',
    directDamage: 20,
    fireRateMs: 800,
    range: 300,
    splashRadius: 0,
    splashFalloff: false,
    penetration: false,
    maxPenetrationTargets: 0,
    selfDamageScale: 0,
    // BLOCKOUT-07H+
    damageKind: 'direct',
    rangePx: 250,
  },
  thunder: {
    weaponId: 'thunder',
    directDamage: 25,
    fireRateMs: 1200,
    range: 250,
    splashRadius: 60,
    splashFalloff: true,
    penetration: false,
    maxPenetrationTargets: 0,
    selfDamageScale: 0.3,
    // BLOCKOUT-07H+
    damageKind: 'splash',
    rangePx: 200,
    radiusPx: 60,
  },
  railgun: {
    weaponId: 'railgun',
    directDamage: 40,
    fireRateMs: 3000,
    range: 600,
    splashRadius: 0,
    splashFalloff: false,
    penetration: true,
    maxPenetrationTargets: 3,
    selfDamageScale: 0,
    // BLOCKOUT-07H+
    damageKind: 'penetration',
    rangePx: 400,
    pierceCount: 3,
  },
  shaft: {
    weaponId: 'shaft',
    directDamage: 60,
    fireRateMs: 4000,
    range: 700,
    splashRadius: 0,
    splashFalloff: false,
    penetration: false,
    maxPenetrationTargets: 0,
    selfDamageScale: 0,
    // BLOCKOUT-07H+
    damageKind: 'direct',
    rangePx: 450,
  },
  flamethrower: {
    weaponId: 'flamethrower',
    damagePerSecond: 30,
    fireRateMs: 50,
    range: 120,
    splashRadius: 0,
    splashFalloff: false,
    penetration: false,
    maxPenetrationTargets: 0,
    statusEffect: 'burn',
    statusDurationMs: 3000,
    selfDamageScale: 0,
    // BLOCKOUT-07H+
    damageKind: 'cone_tick',
    rangePx: 120,
    coneAngleDeg: 25,
    tickMs: 50,
    statusTag: 'burn',
  },
  freeze: {
    weaponId: 'freeze',
    damagePerSecond: 15,
    fireRateMs: 50,
    range: 120,
    splashRadius: 0,
    splashFalloff: false,
    penetration: false,
    maxPenetrationTargets: 0,
    statusEffect: 'freeze',
    statusDurationMs: 2000,
    selfDamageScale: 0,
    // BLOCKOUT-07H+
    damageKind: 'cone_tick',
    rangePx: 120,
    coneAngleDeg: 25,
    tickMs: 50,
    statusTag: 'freeze',
  },
  isida: {
    weaponId: 'isida',
    damagePerSecond: 25,
    fireRateMs: 50,
    range: 150,
    splashRadius: 0,
    splashFalloff: false,
    penetration: false,
    maxPenetrationTargets: 0,
    statusEffect: 'heal',
    statusDurationMs: 0,
    selfDamageScale: 0,
    // BLOCKOUT-07H+
    damageKind: 'beam_tick',
    rangePx: 150,
    tickMs: 50,
    statusTag: 'beam',
  },
  vulcan: {
    weaponId: 'vulcan',
    directDamage: 5,
    fireRateMs: 100,
    range: 280,
    splashRadius: 0,
    splashFalloff: false,
    penetration: false,
    maxPenetrationTargets: 0,
    statusEffect: 'overheat',
    statusDurationMs: 5000,
    selfDamageScale: 0,
    // BLOCKOUT-07H+
    damageKind: 'rapid_tick',
    rangePx: 200,
    tickMs: 100,
    statusTag: 'overheat',
  },
  twins: {
    weaponId: 'twins',
    directDamage: 12,
    fireRateMs: 400,
    range: 250,
    splashRadius: 0,
    splashFalloff: false,
    penetration: false,
    maxPenetrationTargets: 0,
    selfDamageScale: 0,
    // BLOCKOUT-07H+
    damageKind: 'plasma',
    rangePx: 220,
  },
  ricochet: {
    weaponId: 'ricochet',
    directDamage: 18,
    fireRateMs: 1000,
    range: 300,
    splashRadius: 0,
    splashFalloff: false,
    penetration: false,
    maxPenetrationTargets: 0,
    selfDamageScale: 0,
    // BLOCKOUT-07H+
    damageKind: 'ricochet',
    rangePx: 200,
  },
  hammer: {
    weaponId: 'hammer',
    directDamage: 35,
    fireRateMs: 2000,
    range: 100,
    splashRadius: 0,
    splashFalloff: false,
    penetration: false,
    maxPenetrationTargets: 0,
    selfDamageScale: 0,
    // BLOCKOUT-07H+
    damageKind: 'shotgun',
    rangePx: 150,
    pelletCount: 5,
    coneAngleDeg: 30,
  },
};
