/**
 * Blockout damage data — damage profiles per weapon.
 *
 * Blockout placeholder — NOT used in BLOCKOUT-02H.
 * No damage behavior in this PR.
 * Data exists so profiles are complete for future steps.
 *
 * BLOCKOUT-02H: First visible blockout vehicles.
 */

import type { DamageProfile } from './blockoutProfiles';

/** Damage profiles keyed by weapon ID. */
export const DAMAGE_PROFILES: Record<string, DamageProfile> = {
  smoky: {
    weaponId: 'smoky',
    directDamage: 20,
    fireRateMs: 800,
    range: 300,
    splashRadius: 0,
    splashFalloff: false,
    penetration: false,
    maxPenetrationTargets: 0,
    selfDamageScale: 0,
  },
  thunder: {
    weaponId: 'thunder',
    directDamage: 25,
    fireRateMs: 1200,
    range: 250,
    splashRadius: 60,
    splashFalloff: true,
    penetration: false,
    maxPenetrationTargets: 0,
    selfDamageScale: 0.3,
  },
  railgun: {
    weaponId: 'railgun',
    directDamage: 40,
    fireRateMs: 3000,
    range: 600,
    splashRadius: 0,
    splashFalloff: false,
    penetration: true,
    maxPenetrationTargets: 3,
    selfDamageScale: 0,
  },
  shaft: {
    weaponId: 'shaft',
    directDamage: 60,
    fireRateMs: 4000,
    range: 700,
    splashRadius: 0,
    splashFalloff: false,
    penetration: false,
    maxPenetrationTargets: 0,
    selfDamageScale: 0,
  },
  flamethrower: {
    weaponId: 'flamethrower',
    damagePerSecond: 30,
    fireRateMs: 50,
    range: 120,
    splashRadius: 0,
    splashFalloff: false,
    penetration: false,
    maxPenetrationTargets: 0,
    statusEffect: 'burn',
    statusDurationMs: 3000,
    selfDamageScale: 0,
  },
  freeze: {
    weaponId: 'freeze',
    damagePerSecond: 15,
    fireRateMs: 50,
    range: 120,
    splashRadius: 0,
    splashFalloff: false,
    penetration: false,
    maxPenetrationTargets: 0,
    statusEffect: 'freeze',
    statusDurationMs: 2000,
    selfDamageScale: 0,
  },
  isida: {
    weaponId: 'isida',
    damagePerSecond: 25,
    fireRateMs: 50,
    range: 150,
    splashRadius: 0,
    splashFalloff: false,
    penetration: false,
    maxPenetrationTargets: 0,
    statusEffect: 'heal',
    statusDurationMs: 0,
    selfDamageScale: 0,
  },
  vulcan: {
    weaponId: 'vulcan',
    directDamage: 5,
    fireRateMs: 100,
    range: 280,
    splashRadius: 0,
    splashFalloff: false,
    penetration: false,
    maxPenetrationTargets: 0,
    statusEffect: 'overheat',
    statusDurationMs: 5000,
    selfDamageScale: 0,
  },
  twins: {
    weaponId: 'twins',
    directDamage: 12,
    fireRateMs: 400,
    range: 250,
    splashRadius: 0,
    splashFalloff: false,
    penetration: false,
    maxPenetrationTargets: 0,
    selfDamageScale: 0,
  },
  ricochet: {
    weaponId: 'ricochet',
    directDamage: 18,
    fireRateMs: 1000,
    range: 300,
    splashRadius: 0,
    splashFalloff: false,
    penetration: false,
    maxPenetrationTargets: 0,
    selfDamageScale: 0,
  },
  hammer: {
    weaponId: 'hammer',
    directDamage: 35,
    fireRateMs: 2000,
    range: 100,
    splashRadius: 0,
    splashFalloff: false,
    penetration: false,
    maxPenetrationTargets: 0,
    selfDamageScale: 0,
  },
};
