/**
 * Blockout VFX data — VFX profiles per weapon behavior.
 *
 * BLOCKOUT-02H: First visible blockout vehicles (placeholder data).
 * BLOCKOUT-05H+: Extended with rendering config for Smoky/Railgun/Thunder.
 * Other weapon behaviors have placeholder values for future steps.
 */

import type { VfxProfile } from './blockoutProfiles';
import { getWeaponProfile } from './blockoutWeaponData';
import { WEAPON_VFX_ASSET_KEYS } from '../assets/weaponVfxAssets';

/** VFX profiles keyed by weapon behavior. */
export const VFX_PROFILES: Record<string, VfxProfile> = {
  instant_projectile: {
    behavior: 'instant_projectile',
    primitiveType: 'ray',
    color: 0xffff00,
    width: 2,
    durationMs: 150,
    secondaryColor: 0xffaa00,
    impactRadiusPx: 4,
    muzzleFlashRadiusPx: 5,
    effectLengthPx: 250,
    muzzleTextureKey: WEAPON_VFX_ASSET_KEYS.MUZZLE_FLARE,
    trailTextureKey: WEAPON_VFX_ASSET_KEYS.TRAIL,
    impactTextureKey: WEAPON_VFX_ASSET_KEYS.IMPACT_SPARK,
    muzzleTextureSizePx: 30,
    trailTextureWidthPx: 8,
    impactTextureSizePx: 28,
  },
  instant_splash: {
    behavior: 'instant_splash',
    primitiveType: 'circle',
    color: 0xff6600,
    width: 0,
    durationMs: 300,
    secondaryColor: 0xff3300,
    impactRadiusPx: 40,
    muzzleFlashRadiusPx: 4,
    effectLengthPx: 200,
    muzzleTextureKey: WEAPON_VFX_ASSET_KEYS.MUZZLE_FLARE,
    trailTextureKey: WEAPON_VFX_ASSET_KEYS.TRAIL,
    impactTextureKey: WEAPON_VFX_ASSET_KEYS.EXPLOSION,
    smokeTextureKey: WEAPON_VFX_ASSET_KEYS.ROUND_SMOKE,
    muzzleTextureSizePx: 34,
    trailTextureWidthPx: 10,
    impactTextureSizePx: 86,
    smokeTextureSizePx: 64,
  },
  line_pierce: {
    behavior: 'line_pierce',
    primitiveType: 'line',
    color: 0x00ffff,
    width: 2,
    durationMs: 200,
    secondaryColor: 0x88ffff,
    impactRadiusPx: 0,
    muzzleFlashRadiusPx: 6,
    effectLengthPx: 400,
    muzzleTextureKey: WEAPON_VFX_ASSET_KEYS.ENERGY_GLOW,
    trailTextureKey: WEAPON_VFX_ASSET_KEYS.TRAIL,
    impactTextureKey: WEAPON_VFX_ASSET_KEYS.ENERGY_HIT,
    muzzleTextureSizePx: 44,
    trailTextureWidthPx: 12,
    impactTextureSizePx: 44,
  },
  charge_sniper: {
    behavior: 'charge_sniper',
    primitiveType: 'ray',
    color: 0xff00ff,
    width: 3,
    durationMs: 200,
    secondaryColor: 0xff88ff,
    impactRadiusPx: 3,
    muzzleFlashRadiusPx: 4,
    effectLengthPx: 450,
    coneAngleDeg: 0,
    chargePulseMs: 150,
    muzzleTextureKey: WEAPON_VFX_ASSET_KEYS.ENERGY_GLOW,
    trailTextureKey: WEAPON_VFX_ASSET_KEYS.TRAIL,
    impactTextureKey: WEAPON_VFX_ASSET_KEYS.ENERGY_HIT,
    muzzleTextureSizePx: 40,
    trailTextureWidthPx: 8,
    impactTextureSizePx: 36,
  },
  cone_stream: {
    behavior: 'cone_stream',
    primitiveType: 'cone_sector',
    color: 0xff4400,
    width: 0,
    durationMs: 50,
    effectLengthPx: 120,
    coneAngleDeg: 25,
    streamCadenceMs: 50,
    muzzleTextureKey: WEAPON_VFX_ASSET_KEYS.FIRE_STREAM,
    impactTextureKey: WEAPON_VFX_ASSET_KEYS.ROUND_SMOKE,
    noiseTextureKey: WEAPON_VFX_ASSET_KEYS.CLOUD_NOISE,
    muzzleTextureSizePx: 42,
    impactTextureSizePx: 52,
    noiseTextureSizePx: 48,
  },
  beam_support: {
    behavior: 'beam_support',
    primitiveType: 'beam_tether',
    color: 0x00ff88,
    width: 2,
    durationMs: 50,
    effectLengthPx: 150,
    streamCadenceMs: 50,
    muzzleTextureKey: WEAPON_VFX_ASSET_KEYS.ENERGY_GLOW,
    trailTextureKey: WEAPON_VFX_ASSET_KEYS.TRAIL,
    impactTextureKey: WEAPON_VFX_ASSET_KEYS.ENERGY_GLOW,
    muzzleTextureSizePx: 30,
    trailTextureWidthPx: 9,
    impactTextureSizePx: 30,
  },
  rapid_fire_overheat: {
    behavior: 'rapid_fire_overheat',
    primitiveType: 'ray',
    color: 0xffaa00,
    width: 1,
    durationMs: 60,
    muzzleFlashRadiusPx: 3,
    effectLengthPx: 200,
    streamCadenceMs: 60,
    overheatDurationMs: 3000,
    muzzleTextureKey: WEAPON_VFX_ASSET_KEYS.MUZZLE_FLARE,
    trailTextureKey: WEAPON_VFX_ASSET_KEYS.TRAIL,
    impactTextureKey: WEAPON_VFX_ASSET_KEYS.IMPACT_SPARK,
    smokeTextureKey: WEAPON_VFX_ASSET_KEYS.ROUND_SMOKE,
    muzzleTextureSizePx: 24,
    trailTextureWidthPx: 6,
    impactTextureSizePx: 24,
    smokeTextureSizePx: 34,
  },
  plasma_projectile: {
    behavior: 'plasma_projectile',
    primitiveType: 'projectile_dot',
    color: 0x88ff00,
    width: 3,
    durationMs: 200,
    effectLengthPx: 220,
    muzzleFlashRadiusPx: 3,
    streamCadenceMs: 600,
    muzzleTextureKey: WEAPON_VFX_ASSET_KEYS.ENERGY_GLOW,
    trailTextureKey: WEAPON_VFX_ASSET_KEYS.TRAIL,
    impactTextureKey: WEAPON_VFX_ASSET_KEYS.ENERGY_HIT,
    muzzleTextureSizePx: 28,
    trailTextureWidthPx: 12,
    impactTextureSizePx: 34,
  },
  ricochet_projectile: {
    behavior: 'ricochet_projectile',
    primitiveType: 'bounce_marker',
    color: 0xff0088,
    width: 3,
    durationMs: 300,
    effectLengthPx: 200,
    bounceCount: 2,
    muzzleTextureKey: WEAPON_VFX_ASSET_KEYS.ENERGY_GLOW,
    trailTextureKey: WEAPON_VFX_ASSET_KEYS.TRAIL,
    impactTextureKey: WEAPON_VFX_ASSET_KEYS.ENERGY_HIT,
    muzzleTextureSizePx: 30,
    trailTextureWidthPx: 10,
    impactTextureSizePx: 34,
  },
  shotgun_cone: {
    behavior: 'shotgun_cone',
    primitiveType: 'ray',
    color: 0xffcc00,
    width: 1,
    durationMs: 80,
    muzzleFlashRadiusPx: 6,
    effectLengthPx: 150,
    coneAngleDeg: 30,
    pelletCount: 5,
    muzzleTextureKey: WEAPON_VFX_ASSET_KEYS.HAMMER_BLAST,
    trailTextureKey: WEAPON_VFX_ASSET_KEYS.TRAIL,
    impactTextureKey: WEAPON_VFX_ASSET_KEYS.IMPACT_SPARK,
    smokeTextureKey: WEAPON_VFX_ASSET_KEYS.ROUND_SMOKE,
    muzzleTextureSizePx: 52,
    trailTextureWidthPx: 7,
    impactTextureSizePx: 28,
    smokeTextureSizePx: 42,
  },
};

/** Ordered list of all VFX behavior keys. */
export const ALL_VFX_BEHAVIORS = Object.keys(VFX_PROFILES);

/**
 * Get VFX profile for a specific weapon by looking up its behavior.
 * BLOCKOUT-05H+: Convenience helper that chains weaponId -> behavior -> VfxProfile.
 */
export function getWeaponVfxProfile(weaponId: string): VfxProfile | undefined {
  const weapon = getWeaponProfile(weaponId);
  if (!weapon) return undefined;
  return VFX_PROFILES[weapon.vfxProfile];
}
