/**
 * Blockout movement data — movement profiles per body.
 *
 * BLOCKOUT-02H: First visible blockout vehicles.
 * BLOCKOUT-04H+: Added pixel-speed fields for semi-physics movement.
 * Vehicles now accelerate, brake, and turn gradually.
 * Abstract maxSpeed/acceleration values remain for reference;
 * pixel-speed fields are what the movement update actually uses.
 */

import type { MovementProfile } from './blockoutProfiles';

/** Movement profiles keyed by body ID. */
export const MOVEMENT_PROFILES: Record<string, MovementProfile> = {
  wasp: {
    bodyId: 'wasp',
    maxSpeed: 13.0,
    acceleration: 8.0,
    braking: 6.0,
    turnSpeedDeg: 150,
    turnAccelerationDeg: 200,
    lateralAcceleration: 3.0,
    massKg: 2200,
    enginePower: 1300,
    bodyRotationLag: 0.1,
    maxSpeedPxPerSec: 200,
    accelerationPxPerSec2: 240,
    brakingPxPerSec2: 180,
    arrivalRadiusPx: 8,
  },
  hornet: {
    bodyId: 'hornet',
    maxSpeed: 12.0,
    acceleration: 7.0,
    braking: 5.5,
    turnSpeedDeg: 130,
    turnAccelerationDeg: 180,
    lateralAcceleration: 2.5,
    massKg: 2400,
    enginePower: 1400,
    bodyRotationLag: 0.15,
    maxSpeedPxPerSec: 180,
    accelerationPxPerSec2: 210,
    brakingPxPerSec2: 165,
    arrivalRadiusPx: 8,
  },
  hunter: {
    bodyId: 'hunter',
    maxSpeed: 10.0,
    acceleration: 5.5,
    braking: 4.5,
    turnSpeedDeg: 140,
    turnAccelerationDeg: 160,
    lateralAcceleration: 2.0,
    massKg: 3000,
    enginePower: 1400,
    bodyRotationLag: 0.2,
    maxSpeedPxPerSec: 150,
    accelerationPxPerSec2: 165,
    brakingPxPerSec2: 135,
    arrivalRadiusPx: 10,
  },
  viking: {
    bodyId: 'viking',
    maxSpeed: 9.0,
    acceleration: 5.0,
    braking: 4.0,
    turnSpeedDeg: 110,
    turnAccelerationDeg: 140,
    lateralAcceleration: 1.8,
    massKg: 3000,
    enginePower: 1500,
    bodyRotationLag: 0.25,
    maxSpeedPxPerSec: 135,
    accelerationPxPerSec2: 150,
    brakingPxPerSec2: 120,
    arrivalRadiusPx: 10,
  },
  dictator: {
    bodyId: 'dictator',
    maxSpeed: 8.0,
    acceleration: 4.5,
    braking: 3.5,
    turnSpeedDeg: 130,
    turnAccelerationDeg: 160,
    lateralAcceleration: 2.0,
    massKg: 3300,
    enginePower: 1500,
    bodyRotationLag: 0.2,
    maxSpeedPxPerSec: 120,
    accelerationPxPerSec2: 135,
    brakingPxPerSec2: 105,
    arrivalRadiusPx: 12,
  },
  titan: {
    bodyId: 'titan',
    maxSpeed: 6.0,
    acceleration: 3.0,
    braking: 2.5,
    turnSpeedDeg: 90,
    turnAccelerationDeg: 100,
    lateralAcceleration: 1.2,
    massKg: 5000,
    enginePower: 1600,
    bodyRotationLag: 0.4,
    maxSpeedPxPerSec: 90,
    accelerationPxPerSec2: 90,
    brakingPxPerSec2: 75,
    arrivalRadiusPx: 14,
  },
  mammoth: {
    bodyId: 'mammoth',
    maxSpeed: 5.0,
    acceleration: 2.5,
    braking: 2.0,
    turnSpeedDeg: 80,
    turnAccelerationDeg: 90,
    lateralAcceleration: 1.0,
    massKg: 5500,
    enginePower: 1500,
    bodyRotationLag: 0.5,
    maxSpeedPxPerSec: 75,
    accelerationPxPerSec2: 75,
    brakingPxPerSec2: 60,
    arrivalRadiusPx: 16,
  },
};
