/**
 * Tests for TankViewer Composite Spike metadata and helpers.
 *
 * WEBEXPORTER-SPIKE-01: Wasp M0 3-layer compositing proof.
 *
 * The actual compositing logic lives in a standalone HTML file
 * (spike-composite.html) and uses Canvas2D, so it cannot be directly
 * unit-tested in Node.js. Instead, these tests verify the pure
 * metadata constants and manifest structure that the spike produces.
 */

import { describe, it, expect } from 'vitest';

// ─── Faction paint presets ──────────────────────────────────────────
// Must match the FACTION_PAINTS constant in spike-composite.html.

const FACTION_PAINTS: Record<string, { r: number; g: number; b: number; css: string }> = {
  green:  { r: 64,  g: 70,  b: 36,  css: 'rgb(64, 70, 36)' },
  purple: { r: 120, g: 0,   b: 180, css: 'rgb(120, 0, 180)' },
  yellow: { r: 230, g: 200, b: 0,   css: 'rgb(230, 200, 0)' },
  cyan:   { r: 0,   g: 180, b: 200, css: 'rgb(0, 180, 200)' },
};

// ─── Material modes ─────────────────────────────────────────────────
// Must match the MATERIAL_MODES constant in spike-composite.html.

const MATERIAL_MODES = ['raw', 'tankviewer-composite'] as const;

// ─── Manifest type ──────────────────────────────────────────────────
// Mirrors the manifest structure generated by spike-composite.html.

interface TankviewerManifest {
  version: number;
  pipeline: string;
  name: string;
  faction: string;
  directions: number;
  directionConvention: string;
  rotationOffsetDeg: number;
  resolution: number;
  materialMode: string;
  paint: {
    faction: string;
    color: string;
  } | null;
  autoFit: {
    enabled: boolean;
    [key: string]: unknown;
  };
  orthoScale: number;
  sourceConfig: {
    enabled: boolean;
    [key: string]: unknown;
  };
  entries: Array<{
    key: string;
    direction: number;
    directionName: string;
    angleDeg: number;
    filename: string;
  }>;
}

// ─── Helper: build a sample manifest ────────────────────────────────

function buildSampleManifest(
  materialMode: string,
  factionPaint: string,
): TankviewerManifest {
  const paint = FACTION_PAINTS[factionPaint];
  return {
    version: 3,
    pipeline: 'tankviewer-web-isometric',
    name: 'wasp_m0_hull',
    faction: factionPaint,
    directions: 16,
    directionConvention: 'E=0, SE=1, S=2, SW=3, W=4, NW=5, N=6, NE=7',
    rotationOffsetDeg: -90,
    resolution: 256,
    materialMode,
    paint: materialMode === 'tankviewer-composite' && paint
      ? { faction: factionPaint, color: paint.css }
      : null,
    autoFit: { enabled: true, targetSize: 3.0 },
    orthoScale: 4.0,
    sourceConfig: { enabled: false },
    entries: [
      {
        key: `wasp_m0_hull_${factionPaint}_dir0`,
        direction: 0,
        directionName: 'E',
        angleDeg: -90,
        filename: `wasp_m0_hull_${factionPaint}_dir0.png`,
      },
    ],
  };
}

// ─── Tests ──────────────────────────────────────────────────────────

describe('WEBEXPORTER-SPIKE-01: Faction paint presets', () => {
  it('should have exactly 4 faction paint presets', () => {
    const keys = Object.keys(FACTION_PAINTS);
    expect(keys).toHaveLength(4);
  });

  it('should have green, purple, yellow, cyan as preset keys', () => {
    expect(Object.keys(FACTION_PAINTS)).toEqual(
      expect.arrayContaining(['green', 'purple', 'yellow', 'cyan']),
    );
  });

  it('each preset should have r, g, b in 0-255 range', () => {
    for (const [, paint] of Object.entries(FACTION_PAINTS)) {
      expect(paint.r).toBeGreaterThanOrEqual(0);
      expect(paint.r).toBeLessThanOrEqual(255);
      expect(paint.g).toBeGreaterThanOrEqual(0);
      expect(paint.g).toBeLessThanOrEqual(255);
      expect(paint.b).toBeGreaterThanOrEqual(0);
      expect(paint.b).toBeLessThanOrEqual(255);
    }
  });

  it('each preset should have a css property matching rgb(r, g, b)', () => {
    for (const [name, paint] of Object.entries(FACTION_PAINTS)) {
      const expected = `rgb(${paint.r}, ${paint.g}, ${paint.b})`;
      expect(paint.css).toBe(expected);
    }
  });

  it('green paint should match archive value (64, 70, 36)', () => {
    expect(FACTION_PAINTS.green.r).toBe(64);
    expect(FACTION_PAINTS.green.g).toBe(70);
    expect(FACTION_PAINTS.green.b).toBe(36);
  });
});

describe('WEBEXPORTER-SPIKE-01: Material modes', () => {
  it('should have exactly 2 material modes', () => {
    expect(MATERIAL_MODES).toHaveLength(2);
  });

  it('should have "raw" as the first mode (default)', () => {
    expect(MATERIAL_MODES[0]).toBe('raw');
  });

  it('should have "tankviewer-composite" as the second mode', () => {
    expect(MATERIAL_MODES[1]).toBe('tankviewer-composite');
  });

  it('material mode names should be lowercase with hyphens', () => {
    for (const mode of MATERIAL_MODES) {
      expect(mode).toMatch(/^[a-z][a-z0-9-]*$/);
    }
  });
});

describe('WEBEXPORTER-SPIKE-01: Manifest with composite mode', () => {
  it('manifest should record materialMode = "tankviewer-composite"', () => {
    const manifest = buildSampleManifest('tankviewer-composite', 'green');
    expect(manifest.materialMode).toBe('tankviewer-composite');
  });

  it('manifest should record paint faction and color in composite mode', () => {
    const manifest = buildSampleManifest('tankviewer-composite', 'purple');
    expect(manifest.paint).not.toBeNull();
    expect(manifest.paint!.faction).toBe('purple');
    expect(manifest.paint!.color).toBe(FACTION_PAINTS.purple.css);
  });

  it('manifest paint should be null in raw mode', () => {
    const manifest = buildSampleManifest('raw', 'green');
    expect(manifest.materialMode).toBe('raw');
    expect(manifest.paint).toBeNull();
  });

  it('manifest should record correct faction paint color for each preset', () => {
    for (const [name, paint] of Object.entries(FACTION_PAINTS)) {
      const manifest = buildSampleManifest('tankviewer-composite', name);
      expect(manifest.paint!.faction).toBe(name);
      expect(manifest.paint!.color).toBe(paint.css);
    }
  });

  it('manifest sourceConfig should remain intact regardless of material mode', () => {
    const rawManifest = buildSampleManifest('raw', 'green');
    const compositeManifest = buildSampleManifest('tankviewer-composite', 'green');
    expect(rawManifest.sourceConfig).toEqual(compositeManifest.sourceConfig);
    expect(rawManifest.sourceConfig.enabled).toBe(false);
  });

  it('manifest should include version 3', () => {
    const manifest = buildSampleManifest('tankviewer-composite', 'cyan');
    expect(manifest.version).toBe(3);
  });

  it('manifest pipeline should be tankviewer-web-isometric', () => {
    const manifest = buildSampleManifest('tankviewer-composite', 'yellow');
    expect(manifest.pipeline).toBe('tankviewer-web-isometric');
  });

  it('manifest entries should include direction info', () => {
    const manifest = buildSampleManifest('tankviewer-composite', 'green');
    expect(manifest.entries.length).toBeGreaterThan(0);
    expect(manifest.entries[0]).toHaveProperty('direction');
    expect(manifest.entries[0]).toHaveProperty('directionName');
    expect(manifest.entries[0]).toHaveProperty('filename');
  });
});

describe('WEBEXPORTER-SPIKE-01: Compositing formula metadata', () => {
  it('formula should follow: HARDLIGHT(colormap, MULTIPLY(lightmap, details))', () => {
    // This test documents the expected compositing order.
    // The actual Canvas2D implementation is in spike-composite.html.
    const steps = [
      { operation: 'source-over', source: 'details', description: 'Draw details as base' },
      { operation: 'multiply',    source: 'lightmap', description: 'Multiply lightmap over base' },
      { operation: 'hard-light',  source: 'colormap', description: 'Apply paint with hard-light blend' },
      { operation: 'alpha-restore', source: 'details-alpha', description: 'Restore alpha from details PNG' },
    ];
    expect(steps).toHaveLength(4);
    expect(steps[0].operation).toBe('source-over');
    expect(steps[1].operation).toBe('multiply');
    expect(steps[2].operation).toBe('hard-light');
    expect(steps[3].operation).toBe('alpha-restore');
  });

  it('composite mode should use MeshBasicMaterial (no dynamic lighting)', () => {
    // In composite mode, the lightmap is baked into the texture,
    // so MeshBasicMaterial is used instead of MeshStandardMaterial.
    const compositeMaterialType = 'MeshBasicMaterial';
    const requiresLighting = false;
    expect(compositeMaterialType).toBe('MeshBasicMaterial');
    expect(requiresLighting).toBe(false);
  });

  it('raw mode should use MeshStandardMaterial with lighting', () => {
    const rawMaterialType = 'MeshStandardMaterial';
    const requiresLighting = true;
    expect(rawMaterialType).toBe('MeshStandardMaterial');
    expect(requiresLighting).toBe(true);
  });
});
