/* eslint-disable */
// Auto-generated by MODULAR_CYAN_PACKAGER_V1.
// Do not edit manually. Do not preload the whole matrix at startup.

export const GENERATED_MODULAR_HULLS = ["dictator", "hornet", "hunter", "mammoth", "titan", "viking", "wasp"] as const;
export const GENERATED_MODULAR_TURRETS = ["firebird", "freeze", "hammer", "isida", "railgun", "ricochet", "smoky", "thunder", "twins", "vulcan_b"] as const;
export const GENERATED_MODULAR_FACTIONS = ["cyan"] as const;
export const GENERATED_MODULAR_MODS = ["m0", "m1", "m2", "m3"] as const;

export type GeneratedModularHullId = typeof GENERATED_MODULAR_HULLS[number];
export type GeneratedModularTurretId = typeof GENERATED_MODULAR_TURRETS[number];
export type GeneratedModularFactionId = typeof GENERATED_MODULAR_FACTIONS[number];
export type GeneratedModularModId = typeof GENERATED_MODULAR_MODS[number];
export type GeneratedModularDir16 = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15;

const DIR_SUFFIXES: Record<GeneratedModularDir16, string> = {
  0: "E", 1: "ESE", 2: "SE", 3: "SSE", 4: "S", 5: "SSW", 6: "SW", 7: "WSW",
  8: "W", 9: "WNW", 10: "NW", 11: "NNW", 12: "N", 13: "NNE", 14: "NE", 15: "ENE",
};

export function mapRuntimeDir8ToGeneratedDir16(dir8: number): GeneratedModularDir16 {
  const normalized = ((Math.round(dir8) % 8) + 8) % 8;
  return (normalized * 2) as GeneratedModularDir16;
}

export function modificationLevelToGeneratedMod(level: number): GeneratedModularModId {
  const clamped = Math.max(0, Math.min(3, Math.round(level)));
  return (`m${clamped}`) as GeneratedModularModId;
}

export function getGeneratedHullTextureKey(
  hull: GeneratedModularHullId,
  faction: GeneratedModularFactionId,
  mod: GeneratedModularModId,
  dir16: GeneratedModularDir16,
): string {
  return `generated_hull_${hull}_${faction}_${mod}_dir${String(dir16).padStart(2, "0")}`;
}

export function getGeneratedTurretTextureKey(
  turret: GeneratedModularTurretId,
  faction: GeneratedModularFactionId,
  mod: GeneratedModularModId,
  dir16: GeneratedModularDir16,
): string {
  return `generated_turret_${turret}_${faction}_${mod}_dir${String(dir16).padStart(2, "0")}`;
}

export function getGeneratedHullAssetPath(
  hull: GeneratedModularHullId,
  faction: GeneratedModularFactionId,
  mod: GeneratedModularModId,
  dir16: GeneratedModularDir16,
): string {
  const suffix = DIR_SUFFIXES[dir16];
  return `assets/units/hulls/${hull}/${faction}/${mod}/${hull}_${faction}_${mod}_dir${String(dir16).padStart(2, "0")}_${suffix}.png`;
}

export function getGeneratedTurretAssetPath(
  turret: GeneratedModularTurretId,
  faction: GeneratedModularFactionId,
  mod: GeneratedModularModId,
  dir16: GeneratedModularDir16,
): string {
  const suffix = DIR_SUFFIXES[dir16];
  return `assets/units/turrets/${turret}/${faction}/${mod}/${turret}_${faction}_${mod}_dir${String(dir16).padStart(2, "0")}_${suffix}.png`;
}

export function preloadGeneratedModularVehicleSet(
  scene: Phaser.Scene,
  hull: GeneratedModularHullId,
  turret: GeneratedModularTurretId,
  faction: GeneratedModularFactionId,
  hullMod: GeneratedModularModId,
  turretMod: GeneratedModularModId,
): void {
  for (let dir16 = 0 as GeneratedModularDir16; dir16 < 16; dir16 = (dir16 + 1) as GeneratedModularDir16) {
    const hullKey = getGeneratedHullTextureKey(hull, faction, hullMod, dir16);
    if (!scene.textures.exists(hullKey)) {
      scene.load.image(hullKey, getGeneratedHullAssetPath(hull, faction, hullMod, dir16));
    }

    const turretKey = getGeneratedTurretTextureKey(turret, faction, turretMod, dir16);
    if (!scene.textures.exists(turretKey)) {
      scene.load.image(turretKey, getGeneratedTurretAssetPath(turret, faction, turretMod, dir16));
    }
  }
}
