/* eslint-disable */
// AUTO-GENERATED by tools/generate_modular_vehicle_metadata.mjs (MODULAR-RUNTIME-01).
// Do NOT edit by hand. Regenerate with: node tools/generate_modular_vehicle_metadata.mjs
//
// Source manifests (committed):
//   public/assets/units/metadata/hull_socket_manifest_modular_cyan_v1.json
//   public/assets/units/metadata/turret_pivot_manifest_modular_cyan_v1.json
//
// Render strategy: fixed_512_frame
// Socket pixel policy: world_origin_projects_to_frame_center
// Therefore every hull socket and every turret pivot projects to the exact
// centre of its 512x512 frame. Composition aligns the turret pivot onto the
// hull socket with NO per-direction offset tables and NO zHeight hack: the
// 3D height is already baked into where the sprite content sits in-frame.

/** A normalized (0..1) anchor in image space. */
export interface ModularVehicleNormalizedAnchor {
  nx: number;
  ny: number;
}

/** Per-family socket/pivot metadata derived from the export manifests. */
export interface ModularVehicleFamilyMeta {
  /** Hull id or turret id. */
  id: string;
  /** Modification tier (m0..m3). */
  mod: string;
  /** Family-default normalized anchor (frame-centre under the fixed_512 policy). */
  normalized: ModularVehicleNormalizedAnchor;
  /** Source image size in pixels. */
  imageSize: { w: number; h: number };
  /** Render strategy recorded by the exporter. */
  renderStrategy: string;
  /** Optional per-direction overrides (dir16 index -> normalized anchor). */
  perDir?: Record<string, ModularVehicleNormalizedAnchor>;
}

/** True when every hull socket projects to frame centre (no offset tables needed). */
export const MODULAR_HULL_SOCKET_ALL_FRAME_CENTERED = true;

/** True when every turret pivot projects to frame centre (no offset tables needed). */
export const MODULAR_TURRET_PIVOT_ALL_FRAME_CENTERED = true;

/** Hull socket metadata keyed by `${hullId}_${hullMod}`. */
export const MODULAR_HULL_SOCKET_META: Record<string, ModularVehicleFamilyMeta> = {
  "dictator_m0": { id: "dictator", mod: "m0", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "dictator_m1": { id: "dictator", mod: "m1", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "dictator_m2": { id: "dictator", mod: "m2", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "dictator_m3": { id: "dictator", mod: "m3", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "hornet_m0": { id: "hornet", mod: "m0", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "hornet_m1": { id: "hornet", mod: "m1", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "hornet_m2": { id: "hornet", mod: "m2", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "hornet_m3": { id: "hornet", mod: "m3", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "hunter_m0": { id: "hunter", mod: "m0", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "hunter_m1": { id: "hunter", mod: "m1", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "hunter_m2": { id: "hunter", mod: "m2", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "hunter_m3": { id: "hunter", mod: "m3", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "mammoth_m0": { id: "mammoth", mod: "m0", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "mammoth_m1": { id: "mammoth", mod: "m1", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "mammoth_m2": { id: "mammoth", mod: "m2", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "mammoth_m3": { id: "mammoth", mod: "m3", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "titan_m0": { id: "titan", mod: "m0", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "titan_m1": { id: "titan", mod: "m1", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "titan_m2": { id: "titan", mod: "m2", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "titan_m3": { id: "titan", mod: "m3", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "viking_m0": { id: "viking", mod: "m0", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "viking_m1": { id: "viking", mod: "m1", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "viking_m2": { id: "viking", mod: "m2", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "viking_m3": { id: "viking", mod: "m3", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "wasp_m0": { id: "wasp", mod: "m0", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "wasp_m1": { id: "wasp", mod: "m1", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "wasp_m2": { id: "wasp", mod: "m2", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "wasp_m3": { id: "wasp", mod: "m3", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
};

/** Turret pivot metadata keyed by `${turretId}_${turretMod}`. */
export const MODULAR_TURRET_PIVOT_META: Record<string, ModularVehicleFamilyMeta> = {
  "firebird_m0": { id: "firebird", mod: "m0", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "firebird_m1": { id: "firebird", mod: "m1", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "firebird_m2": { id: "firebird", mod: "m2", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "firebird_m3": { id: "firebird", mod: "m3", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "freeze_m0": { id: "freeze", mod: "m0", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "freeze_m1": { id: "freeze", mod: "m1", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "freeze_m2": { id: "freeze", mod: "m2", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "freeze_m3": { id: "freeze", mod: "m3", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "hammer_m0": { id: "hammer", mod: "m0", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "hammer_m1": { id: "hammer", mod: "m1", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "hammer_m2": { id: "hammer", mod: "m2", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "hammer_m3": { id: "hammer", mod: "m3", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "isida_m0": { id: "isida", mod: "m0", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "isida_m1": { id: "isida", mod: "m1", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "isida_m2": { id: "isida", mod: "m2", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "isida_m3": { id: "isida", mod: "m3", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "railgun_m0": { id: "railgun", mod: "m0", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "railgun_m1": { id: "railgun", mod: "m1", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "railgun_m2": { id: "railgun", mod: "m2", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "railgun_m3": { id: "railgun", mod: "m3", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "ricochet_m0": { id: "ricochet", mod: "m0", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "ricochet_m1": { id: "ricochet", mod: "m1", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "ricochet_m2": { id: "ricochet", mod: "m2", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "ricochet_m3": { id: "ricochet", mod: "m3", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "smoky_m0": { id: "smoky", mod: "m0", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "smoky_m1": { id: "smoky", mod: "m1", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "smoky_m2": { id: "smoky", mod: "m2", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "smoky_m3": { id: "smoky", mod: "m3", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "thunder_m0": { id: "thunder", mod: "m0", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "thunder_m1": { id: "thunder", mod: "m1", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "thunder_m2": { id: "thunder", mod: "m2", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "thunder_m3": { id: "thunder", mod: "m3", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "twins_m0": { id: "twins", mod: "m0", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "twins_m1": { id: "twins", mod: "m1", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "twins_m2": { id: "twins", mod: "m2", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "twins_m3": { id: "twins", mod: "m3", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "vulcan_b_m0": { id: "vulcan_b", mod: "m0", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "vulcan_b_m1": { id: "vulcan_b", mod: "m1", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "vulcan_b_m2": { id: "vulcan_b", mod: "m2", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
  "vulcan_b_m3": { id: "vulcan_b", mod: "m3", normalized: { nx: 0.5, ny: 0.5 }, imageSize: { w: 512, h: 512 }, renderStrategy: "fixed_512_frame" },
};
