/**
 * Auto-generated runtime asset manifest.
 *
 * DO NOT EDIT — this file is generated by tools/process_art_assets.mjs.
 * Any manual changes will be overwritten on the next processor run.
 */

export const GENERATED_ASSET_MANIFEST = {
  version: 1,
  generatedAt: '1970-01-01T00:00:00.000Z',
  families: {
    hq: {
      keys: ['hq_cyan', 'hq_green', 'hq_yellow', 'hq_purple'],
      loadType: 'image',
      enabled: true,
    },
    buildings: {
      keys: ['building_cyan_separator', 'building_cyan_raw_storage', 'building_cyan_matter_storage', 'building_cyan_power_plant', 'building_cyan_command_relay', 'building_cyan_units_factory', 'building_green_separator', 'building_green_raw_storage', 'building_green_matter_storage', 'building_green_power_plant', 'building_green_command_relay', 'building_green_units_factory', 'building_yellow_separator', 'building_yellow_raw_storage', 'building_yellow_matter_storage', 'building_yellow_power_plant', 'building_yellow_command_relay', 'building_yellow_units_factory', 'building_purple_separator', 'building_purple_raw_storage', 'building_purple_matter_storage', 'building_purple_power_plant', 'building_purple_command_relay', 'building_purple_units_factory'],
      loadType: 'image',
      enabled: true,
    },
    civilUnits: {
      keys: ['builder_cyan', 'harvester_cyan', 'builder_green', 'harvester_green', 'builder_yellow', 'harvester_yellow', 'builder_purple', 'harvester_purple'],
      loadType: 'spritesheet',
      frameConfig: { frameWidth: 256, frameHeight: 256, endFrame: 63 },
      enabled: true,
    },
  },
  paths: {
    'hq_cyan': 'assets/factions/cyan/buildings/hq_t1.png',
    'hq_green': 'assets/factions/green/buildings/hq_t1.png',
    'hq_yellow': 'assets/factions/yellow/buildings/hq_t1.png',
    'hq_purple': 'assets/factions/purple/buildings/hq_t1.png',
    'building_cyan_separator': 'assets/factions/cyan/buildings/separator.png',
    'building_cyan_raw_storage': 'assets/factions/cyan/buildings/raw_storage.png',
    'building_cyan_matter_storage': 'assets/factions/cyan/buildings/matter_storage.png',
    'building_cyan_power_plant': 'assets/factions/cyan/buildings/power_plant.png',
    'building_cyan_command_relay': 'assets/factions/cyan/buildings/command_relay.png',
    'building_cyan_units_factory': 'assets/factions/cyan/buildings/units_factory.png',
    'building_green_separator': 'assets/factions/green/buildings/separator.png',
    'building_green_raw_storage': 'assets/factions/green/buildings/raw_storage.png',
    'building_green_matter_storage': 'assets/factions/green/buildings/matter_storage.png',
    'building_green_power_plant': 'assets/factions/green/buildings/power_plant.png',
    'building_green_command_relay': 'assets/factions/green/buildings/command_relay.png',
    'building_green_units_factory': 'assets/factions/green/buildings/units_factory.png',
    'building_yellow_separator': 'assets/factions/yellow/buildings/separator.png',
    'building_yellow_raw_storage': 'assets/factions/yellow/buildings/raw_storage.png',
    'building_yellow_matter_storage': 'assets/factions/yellow/buildings/matter_storage.png',
    'building_yellow_power_plant': 'assets/factions/yellow/buildings/power_plant.png',
    'building_yellow_command_relay': 'assets/factions/yellow/buildings/command_relay.png',
    'building_yellow_units_factory': 'assets/factions/yellow/buildings/units_factory.png',
    'building_purple_separator': 'assets/factions/purple/buildings/separator.png',
    'building_purple_raw_storage': 'assets/factions/purple/buildings/raw_storage.png',
    'building_purple_matter_storage': 'assets/factions/purple/buildings/matter_storage.png',
    'building_purple_power_plant': 'assets/factions/purple/buildings/power_plant.png',
    'building_purple_command_relay': 'assets/factions/purple/buildings/command_relay.png',
    'building_purple_units_factory': 'assets/factions/purple/buildings/units_factory.png',
    'builder_cyan': 'assets/factions/cyan/units/builder_8x8_256.png',
    'harvester_cyan': 'assets/factions/cyan/units/harvester_8x8_256.png',
    'builder_green': 'assets/factions/green/units/builder_8x8_256.png',
    'harvester_green': 'assets/factions/green/units/harvester_8x8_256.png',
    'builder_yellow': 'assets/factions/yellow/units/builder_8x8_256.png',
    'harvester_yellow': 'assets/factions/yellow/units/harvester_8x8_256.png',
    'builder_purple': 'assets/factions/purple/units/builder_8x8_256.png',
    'harvester_purple': 'assets/factions/purple/units/harvester_8x8_256.png',
  },
} as const;

export type GeneratedAssetKey = keyof typeof GENERATED_ASSET_MANIFEST.paths;
export type GeneratedAssetFamilyName = keyof typeof GENERATED_ASSET_MANIFEST.families;
